In [92]:
# For First 7 rows in Top Apps in Google Play
import pandas as pd
 
data = pd.read_csv("Top-Apps-in-Google-Play.csv")
df = data.iloc[:7]

df

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False
1,2,YouTube,com.google.android.youtube,Video Players & Editors,Google LLC,https://support.google.com/youtube/topic/24225...,ytandroid-support@google.com,Teen,True,False
2,3,Google,com.google.android.googlequicksearchbox,Tools,Google LLC,https://www.google.com/search/about/,apps-help@google.com,Everyone,True,False
3,4,Google Maps - Navigate & Explore,com.google.android.apps.maps,Travel & Local,Google LLC,http://maps.google.com/about/,apps-help@google.com,Everyone,True,False
4,5,Google Text-to-Speech,com.google.android.tts,Tools,Google LLC,http://www.google.com/,tts-feedback@google.com,Everyone,False,False
5,6,Google Chrome: Fast & Secure,com.android.chrome,Communication,Google LLC,http://www.google.com/chrome/android,apps-help@google.com,Everyone,False,False
6,7,Gmail,com.google.android.gm,Communication,Google LLC,http://support.google.com/mail/bin/topic.py?hl...,apps-help@google.com,Everyone,True,False

In [90]:
# For First 7 rows in Cryptocurrency Predict Artificial Intelligence V3
import pandas as pd
 
data = pd.read_csv("BTC_DATA_V3.0.csv")
df = data.iloc[:7]

df

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%
1  24-Mar-22  44013.0  42911.0  44251.0  42658.0  491.66M    2.57%
2  23-Mar-22  42912.0  42373.0  43027.0  41795.0  433.96M    1.27%
3  22-Mar-22  42373.0  41022.0  43327.9  40893.0  537.06M    3.29%
4  21-Mar-22  41022.0  41282.0  41532.0  40530.0  406.62M   -0.62%
5  20-Mar-22  41276.0  42241.0  42301.0  40922.0  308.45M   -2.27%
6  19-Mar-22  42233.0  41768.0  42386.0  41529.6  224.59M    1.11%

In [88]:
# For First 7 rows in Programming Languages Trend Over Time
import pandas as pd
 
data = pd.read_csv("programming language trend over time.csv")
df = data.iloc[:7]

df

        Week  Python  Java  C++
0  4/21/2019      55    55   18
1  4/28/2019      52    50   16
2   5/5/2019      56    56   17
3  5/12/2019      56    61   18
4  5/19/2019      57    56   17
5  5/26/2019      55    57   17
6   6/2/2019      54    58   15

In [72]:
# For First 3 rows in Top Apps in Google Play
import pandas as pd
 
data = pd.read_csv("Top-Apps-in-Google-Play.csv")
df = data.iloc[:3]

df

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False
1,2,YouTube,com.google.android.youtube,Video Players & Editors,Google LLC,https://support.google.com/youtube/topic/24225...,ytandroid-support@google.com,Teen,True,False
2,3,Google,com.google.android.googlequicksearchbox,Tools,Google LLC,https://www.google.com/search/about/,apps-help@google.com,Everyone,True,False

In [74]:
# For First 3 rows in Cryptocurrency Predict Artificial Intelligence V3
import pandas as pd
 
data = pd.read_csv("BTC_DATA_V3.0.csv")
df = data.iloc[:3]

df

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%
1  24-Mar-22  44013.0  42911.0  44251.0  42658.0  491.66M    2.57%
2  23-Mar-22  42912.0  42373.0  43027.0  41795.0  433.96M    1.27%

In [76]:
# For First 3 rows in Programming Languages Trend Over Time
import pandas as pd
 
data = pd.read_csv("programming language trend over time.csv")
df = data.iloc[:3]

df

        Week  Python  Java  C++
0  4/21/2019      55    55   18
1  4/28/2019      52    50   16
2   5/5/2019      56    56   17

In [80]:
# For first row and header in Top Apps in Google Play
import pandas as pd
 
# making data frame from csv file
data = pd.read_csv("Top-Apps-In-Google-Play.csv")
df = data.head(1)

df

,Unnamed: 0,App Name,App Id,Category,Developer Id,Developer Website,Developer Email,Content Rating,Ad Supported,In App Purchases
0,1,Google Play services,com.google.android.gms,Tools,Google LLC,https://developers.google.com/android/google-p...,apps-help@google.com,Everyone,False,False

In [82]:
# For first row and header in Cryptocurrency Predict Artificial Intelligence V3
import pandas as pd
 
# making data frame from csv file
data = pd.read_csv("BTC_DATA_V3.0.csv")
df = data.head(1)

df

        Date    Price     Open     High      Low     Vol. Change %
0  25-Mar-22  44331.0  44013.0  45112.0  43622.0  494.09M    0.72%

In [84]:
# For first row and header in Programming Languages Trend Over Time
import pandas as pd
 
# making data frame from csv file
data = pd.read_csv("programming language trend over time.csv")
df = data.head(1)

df

        Week  Python  Java  C++
0  4/21/2019      55    55   18